# Generated by Django 4.2.1 on 2023-06-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_person_alter_todo_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='emial',
            new_name='email',
        ),
    ]
